module.exports={
    MONGODB_URL= process.env.MONGODB_URL,
ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET,
REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET,

CLOUD_NAME= dsirbixgj,
CLOUD_API_KEY= process.env.CLOUD_API_KEY,
CLOUD_API_SECRET= process.env.CLOUD_API_SECRET,
}